server:
  port: 8010


spring:
  application:
    name: microservice-consumer-movie

management:
  security:
    enabled: false

### eureka 客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:password123@localhost:8762/eureka/,http://root:password123@localhost:8761/eureka/
    instance:
      prefer-ip-address: true