server:
  port: 8080

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/195286381/spring-cloud-docker-practice-config-repo
          username: 195286381@qq.com
          password: XiaoZhu1990