server:
  port: 8040

spring:
  application:
    name: microservice-gateway-zuul

### eureka 客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://root:password123@localhost:8762/eureka/,http://root:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true