spring:
  application:
    name: microservice-discovery-eureka-ha

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:password123@localhost:8762/eureka/,http://root:password123@localhost:8761/eureka/
security:
  basic:
    enabled: true
  user:
    name: root
    password: password123

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1


---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2