spring:
  profiles:
    active: user-8000
  application:
      name: microservice-provider-user

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate,type.descriptor.sql.BasicBinder: trace
    org.hibernate,type.descriptor.sql.BasicExtractor: trace


management:
  security:
    enabled: false


### eureka 客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:password123@localhost:8762/eureka/,http://root:password123@localhost:8761/eureka/
    instance:
      prefer-ip-address: true

---
spring:
  profiles: user-8000

server:
  port: 8000

---
spring:
  profiles: user-8001

server:
  port: 8001