server:
  port: 8031

spring:
  application:
    name: microservice-hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://root:password123@localhost:8761/eureka,http://root:password123@localhost:8762/eureka,
  instance:
    prefer-ip-address: true

turbine:
  app-config: microservice-consumer-movie
  cluster-name-expression: "'default'"